# Generated by Django 5.1.3 on 2025-12-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, help_text="Book description", null=True),
        ),
    ]
