# Generated by Django 5.1.3 on 2025-12-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non-fiction", "Non-Fiction"),
                    ("science", "Science"),
                    ("history", "History"),
                    ("biography", "Biography"),
                    ("fantasy", "Fantasy"),
                    ("mystery", "Mystery"),
                    ("romance", "Romance"),
                    ("thriller", "Thriller"),
                    ("self-help", "Self-Help"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="readbook",
            name="rating",
            field=models.IntegerField(default=0, help_text="Rating from 1 to 5"),
        ),
    ]
