# Generated by Django 5.1.3 on 2025-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(default="avatar.jpg", editable=False, upload_to=""),
        ),
    ]
